url: "http://ocmock.org"
highlighter: rouge
exclude: [Gemfile, Gemfile.lock, Makefile, run.sh]
permalink: pretty
date_format: "%d %B %Y"
baseurl: "https://erikdoe.github.io/quvyn"
quvynurl: "https://www.mulle-kybernetik.com/quvyn-quvyn"
githuburl: "https://github.com/erikdoe/quvyn"
